### PR TITLE
(XS) WEB | HTML: add browserstack logo to global supporters in footer

### PR DESCRIPTION
**Pull request by ConnorBradley**
Added footer .png, replaced old icon with white background to transparent one. Also halved the size of the image.
Linked to the browserstack site rather than to an AboutUs page. Super easy to link to an about us section if someone wants to create some content for it?

### CODE REVIEW

**Comment by vincelee888** [comment]
hi connor. that image is also used in the readme (see your fork: https://github.com/ConnorBradley/streetsupport-web) does it need to be so tall?

**Comment by ConnorBradley** [comment]
Fixed - Only used git for personal projects so not sure if I've committed the changes properly. 
If you can't see the most recent changes let me know. Cheers.

**Comment by vincelee888** [comment]
hi connor. the image isn't appearing in the footer anymore. in your [previous commit](https://github.com/StreetSupport/streetsupport-web/pull/283/commits/f6cfe25c5446977c79b6138e29a1246d73e7666b), seems to have been reverted.

rather than it just displaying in manchester, it needs to appear globally. can you create a new partial eg "global-footer-supporters.hbs" and put the icon and link markup in there. then you need to include that in each locations footer partials.

also, your PR seems to include a bunch of other stuff (eg bradford content), not related to the ticket in question. i'm going to write a guide on how to keep things a bit cleaner when submitting a PR.

cheers!

**Comment by vincelee888** [comment]
going to bin this off, and create a nice new page for all the tech supporters

**Pull request closed without merging**
